services:
  fxapp:
    build: .
    container_name: fxapp
    ports:
      - "8080:8080"
    env_file:
      - .env.sample
    restart: unless-stopped
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    volumes:
      - redis:/data

volumes:
  postgresql_data:
    driver: local
  redis:
    driver: local
