spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fxdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB

  data:
    redis:
      host: localhost
      port: 6379
      password: password

  cache:
    type: redis

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

---

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

openExchangeRate:
  apiUrl: https://openexchangerates.org/api/latest.json
  apiKey: your_api_key
  interval: 1800000

server:
  port: 8080
